let allProjects = [];
let previousFocus;
const allowedMediaHosts = new Set(["youtube.com", "www.youtube.com", "youtu.be", "canva.com", "www.canva.com"]);
const $ = (id) => document.getElementById(id);
document.addEventListener("DOMContentLoaded", () => {
  $("footer-year").textContent = new Date().getFullYear();
  $("category-filter").addEventListener("change", filterProjects); $("retry-projects").addEventListener("click", loadProjects);
  $("modal-close").addEventListener("click", closeModal); $("project-modal").addEventListener("click", (e) => { if (e.target === $("project-modal")) closeModal(); }); $("project-modal").addEventListener("cancel", (e) => { e.preventDefault(); closeModal(); });
  bindContactForm(); bindCookieDialog(); loadProjects(); loadSiteSettings();
});
function setState(name) { ["loading-state", "error-state", "empty-state"].forEach((id) => $(id).classList.toggle("hidden", id !== name)); }
async function loadProjects() { setState("loading-state"); $("projects-grid").replaceChildren(); const timeout = new Promise((_, reject) => setTimeout(() => reject(new Error("timeout")), 10000)); try { const result = await Promise.race([supabaseClient.from(TABLES.PROJECTS).select("id,title,description,category,images,videos,audios,links,role,year,tools,credits,rights,created_at").order("created_at", { ascending: false }), timeout]); if (result.error) throw result.error; allProjects = result.data || []; populateFilter(); renderProjects(allProjects); setState(allProjects.length ? "none" : "empty"); } catch { setState("error-state"); } }
function populateFilter() { const select = $("category-filter"); const value = select.value; select.replaceChildren(new Option("Todas las categorías", "")); [...new Set(allProjects.map(p => p.category).filter(Boolean))].sort().forEach(c => select.add(new Option(c, c))); select.value = value; }
function filterProjects() { const category = $("category-filter").value; const projects = category ? allProjects.filter(p => p.category === category) : allProjects; renderProjects(projects); setState(projects.length ? "none" : "empty"); if (!projects.length) $("empty-state").textContent = "No hay proyectos en esta categoría."; }
function renderProjects(projects) { const grid = $("projects-grid"); grid.replaceChildren(); projects.forEach((project, index) => { const article = document.createElement("article"); article.className = `project-card project-card-${index % 3}`; const button = document.createElement("button"); button.type = "button"; button.className = "project-open"; button.setAttribute("aria-label", `Ver proyecto: ${project.title}`); const image = project.images?.[0]; if (image && isSafeUrl(image)) { const img = document.createElement("img"); img.src = image; img.alt = project.title ? `Proyecto: ${project.title}` : ""; img.loading = "lazy"; button.append(img); } else { const placeholder = document.createElement("div"); placeholder.className = "project-placeholder"; placeholder.setAttribute("aria-hidden", "true"); button.append(placeholder); } const meta = document.createElement("div"); meta.className = "project-meta"; meta.append(textEl("p", project.category || "Proyecto", "eyebrow"), textEl("h3", project.title || "Sin título"), textEl("p", project.description || "", "project-description")); button.append(meta); button.addEventListener("click", () => openProject(project)); article.append(button); grid.append(article); }); }
function textEl(tag, text, className = "") { const el = document.createElement(tag); el.textContent = text; if (className) el.className = className; return el; }
function isSafeUrl(value) { try { return ["https:", "http:"].includes(new URL(value).protocol); } catch { return false; } }
function externalUrl(value) { try { const url = new URL(value); return allowedMediaHosts.has(url.hostname) || url.hostname.endsWith(".supabase.co"); } catch { return false; } }
function openProject(project) { previousFocus = document.activeElement; const content = $("modal-content"); content.replaceChildren(textEl("p", project.category || "Proyecto", "eyebrow"), textEl("h2", project.title || "Sin título")); if (project.description) content.append(textEl("p", project.description, "modal-description")); [["Rol", project.role], ["Año", project.year], ["Herramientas y técnicas", project.tools], ["Créditos y derechos", [project.credits, project.rights].filter(Boolean).join("\n")]].forEach(([label, value]) => { if (value) { const section = document.createElement("section"); section.append(textEl("h3", label), textEl("p", value)); content.append(section); } }); (project.images || []).filter(isSafeUrl).forEach((url) => { const img = document.createElement("img"); img.src=url; img.alt=`Proyecto: ${project.title || "sin título"}`; img.loading="lazy"; content.append(img); }); (project.videos || []).filter(externalUrl).forEach((url) => { const link=document.createElement("a"); link.href=url; link.target="_blank"; link.rel="noopener noreferrer"; link.textContent="Ver material audiovisual"; content.append(link); }); (project.audios || []).filter(isSafeUrl).forEach((url) => { const audio=document.createElement("audio"); audio.controls=true; audio.src=url; content.append(audio); }); $("project-modal").showModal(); $("modal-close").focus(); }
function closeModal() { const modal = $("project-modal"); if (modal.open) modal.close(); previousFocus?.focus(); }
async function loadSiteSettings() { try { const { data } = await supabaseClient.from(TABLES.CONTACT).select("instagram_url,contact_email").eq("id", 1).maybeSingle(); if (!data) return; if (isSafeUrl(data.instagram_url)) $("footer-instagram").href=data.instagram_url; if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.contact_email || "")) $("footer-email").href=`mailto:${data.contact_email}`; } catch {} }
function bindContactForm() { $("contact-form").addEventListener("submit", async (e) => { e.preventDefault(); const form=e.currentTarget, status=$("contact-status"); if (!form.checkValidity()) { form.reportValidity(); return; } const payload=Object.fromEntries(new FormData(form)); status.textContent="Enviando…"; const button=form.querySelector("button[type=submit]"); button.disabled=true; try { const response=await fetch("/.netlify/functions/contact", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(payload) }); if (!response.ok) throw new Error(); form.reset(); status.textContent="Gracias. Tu mensaje fue enviado."; } catch { status.textContent="No se pudo enviar el mensaje. Inténtalo nuevamente más tarde."; } finally { button.disabled=false; } }); }
function bindCookieDialog() { const dialog=$("cookie-dialog"); const save=(value)=>{ localStorage.setItem("cookie-consent", value); dialog.close(); }; $("cookie-accept").onclick=()=>save("accepted"); $("cookie-reject").onclick=()=>save("rejected"); $("cookie-settings").onclick=()=>dialog.showModal(); if (!localStorage.getItem("cookie-consent")) dialog.showModal(); }
