let allProjects=[],previousFocus;const $=id=>document.getElementById(id),safeUrl=value=>{try{return["https:","http:"].includes(new URL(value).protocol)}catch{return false}},videoMime=value=>typeof value==="string"&&value.startsWith("video/");
function initializePublicPortfolio(){$("footer-year").textContent=new Date().getFullYear();$("category-filter").onchange=filterProjects;$("retry-projects").onclick=loadProjects;$("modal-close").onclick=closeModal;$("project-modal").addEventListener("cancel",e=>{e.preventDefault();closeModal()});$("project-modal").addEventListener("click",e=>{if(e.target===$("project-modal"))closeModal()});bindContactForm();bindCookieDialog();loadProjects();loadSiteSettings()}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",initializePublicPortfolio,{once:true});else initializePublicPortfolio();
function text(tag,value,cls=""){const el=document.createElement(tag);el.textContent=value||"";el.className=cls;return el}function state(name){["loading-state","error-state","empty-state"].forEach(id=>$(id).classList.toggle("hidden",id!==name))}
async function loadProjects(){state("loading-state");$("projects-grid").replaceChildren();try{const {data,error}=await supabaseClient.from(TABLES.PROJECTS).select("id,title,description,category,images,videos,video_assets,audios,role,year,tools,credits,rights,created_at").order("created_at",{ascending:false});if(error)throw error;allProjects=data||[];const s=$("category-filter"),v=s.value;s.replaceChildren(new Option("Todas las categorías",""));[...new Set(allProjects.map(p=>p.category).filter(Boolean))].sort().forEach(x=>s.add(new Option(x,x)));s.value=v;renderProjects(allProjects);state(allProjects.length?"none":"empty")}catch{state("error-state")}}
function filterProjects(){const list=$("category-filter").value?allProjects.filter(p=>p.category===$("category-filter").value):allProjects;renderProjects(list);state(list.length?"none":"empty")}
function storageVideo(project){return(project.video_assets||[]).find(asset=>asset?.source==="storage"&&safeUrl(asset.url)&&videoMime(asset.mime_type))}
function renderProjects(projects){const grid=$("projects-grid");grid.replaceChildren();projects.forEach((p,i)=>{const article=document.createElement("article"),button=document.createElement("button"),asset=storageVideo(p);article.className=`project-card project-card-${i%3}`;button.type="button";button.className="project-open";button.setAttribute("aria-label",`Ver proyecto: ${p.title}`);if(p.images?.[0]&&safeUrl(p.images[0])){const img=document.createElement("img");img.src=p.images[0];img.alt=p.title?`Proyecto: ${p.title}`:"";img.loading="lazy";button.append(img)}else if(asset){const video=document.createElement("video");video.src=asset.url;video.preload="metadata";video.playsInline=true;video.muted=true;video.setAttribute("aria-hidden","true");if(asset.poster_url&&safeUrl(asset.poster_url))video.poster=asset.poster_url;button.append(video)}else{const d=document.createElement("div");d.className="project-placeholder";d.setAttribute("aria-hidden","true");button.append(d)}const meta=document.createElement("div");meta.className="project-meta";meta.append(text("p",p.category||"Proyecto","eyebrow"),text("h3",p.title||"Sin título"),text("p",p.description,"project-description"));button.append(meta);button.onclick=()=>openProject(p);article.append(button);grid.append(article)})}
function mediaVideo(asset){const v=document.createElement("video");v.controls=true;v.preload="metadata";v.playsInline=true;if(asset.poster_url&&safeUrl(asset.poster_url))v.poster=asset.poster_url;const source=document.createElement("source");source.src=asset.playback_url||asset.url;source.type=asset.mime_type;v.append(source,document.createTextNode("Tu navegador no soporta la reproducción de video."));v.addEventListener("error",()=>{const notice=text("p","No se pudo reproducir este video.","media-error");v.replaceWith(notice)});return v}
function openProject(p){previousFocus=document.activeElement;const c=$("modal-content");c.replaceChildren(text("p",p.category||"Proyecto","eyebrow"),text("h2",p.title||"Sin título"));if(p.description)c.append(text("p",p.description,"modal-description"));[["Rol",p.role],["Año",p.year],["Herramientas y técnicas",p.tools],["Créditos y derechos",[p.credits,p.rights].filter(Boolean).join("\n")]].forEach(([h,v])=>{if(v){const s=document.createElement("section");s.append(text("h3",h),text("p",v));c.append(s)}});(p.images||[]).filter(safeUrl).forEach(url=>{const img=document.createElement("img");img.src=url;img.alt=`Proyecto: ${p.title||"sin título"}`;img.loading="lazy";c.append(img)});(p.video_assets||[]).filter(asset=>asset?.source==="storage"&&safeUrl(asset.url)&&videoMime(asset.mime_type)).forEach(asset=>c.append(mediaVideo(asset)));(p.videos||[]).filter(safeUrl).filter(url=>!(p.video_assets||[]).some(a=>a.url===url)).forEach(url=>{const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.textContent="Ver material audiovisual externo";c.append(a)});$("project-modal").showModal();$("modal-close").focus()}
function closeModal(){const m=$("project-modal");if(m.open)m.close();previousFocus?.focus()}
async function loadSiteSettings(){try{const {data}=await supabaseClient.from(TABLES.CONTACT).select("instagram_url,contact_email").eq("id",1).maybeSingle();if(data?.instagram_url&&safeUrl(data.instagram_url))$("footer-instagram").href=data.instagram_url;if(/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data?.contact_email||""))$("footer-email").href=`mailto:${data.contact_email}`}catch{}}
function bindContactForm(){$("contact-form").addEventListener("submit",async e=>{e.preventDefault();const f=e.currentTarget,s=$("contact-status");if(!f.checkValidity())return f.reportValidity();const b=f.querySelector("button[type=submit]");b.disabled=true;s.textContent="Enviando…";try{const r=await fetch("/.netlify/functions/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(f)))});if(!r.ok)throw Error();f.reset();s.textContent="Gracias. Tu mensaje fue enviado."}catch{s.textContent="No se pudo enviar el mensaje. Inténtalo nuevamente más tarde."}finally{b.disabled=false}})}
function bindCookieDialog(){const d=$("cookie-dialog"),save=x=>{localStorage.setItem("cookie-consent",x);d.close()};$("cookie-accept").onclick=()=>save("accepted");$("cookie-reject").onclick=()=>save("rejected");$("cookie-settings").onclick=()=>d.showModal();if(!localStorage.getItem("cookie-consent"))d.showModal()}
