const { createClient } = window.supabase;
const supabaseClient = createClient(SUPABASE_CONFIG.URL, SUPABASE_CONFIG.ANON_KEY);
const VIDEO_TYPES = { mp4: "video/mp4", webm: "video/webm", mov: "video/quicktime" };
const LARGE_UPLOAD_BYTES = 6 * 1024 * 1024;
function cleanStorageName(name) { const extension = name.includes(".") ? `.${name.split(".").pop().toLowerCase()}` : ""; const base = extension ? name.slice(0, -extension.length) : name; return `${base.normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-zA-Z0-9_-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "archivo"}${extension}`; }
function fileExtension(file) { return file.name.split(".").pop().toLowerCase(); }
function mediaType(file) { return file.type || VIDEO_TYPES[fileExtension(file)] || ""; }
function assertStorageConfig() { if (!SUPABASE_CONFIG.BUCKET || typeof SUPABASE_CONFIG.BUCKET !== "string") throw new Error("La configuración del bucket no es válida."); }
function createStoragePath(file, folder) { assertStorageConfig(); const path = `${folder}/${Date.now()}_${cleanStorageName(file.name)}`; if (!file?.name || path.includes("undefined") || path.includes("//")) throw new Error("No se pudo generar una ruta de archivo válida."); return path; }
function publicStorageUrl(path) { return supabaseClient.storage.from(SUPABASE_CONFIG.BUCKET).getPublicUrl(path).data.publicUrl; }
async function uploadFileToStorage(file, folder = "misc") { if (!file || !file.size) throw new Error("Selecciona un archivo válido."); const contentType = mediaType(file); if (!contentType) throw new Error("El archivo no informa un tipo MIME válido."); if (folder === "images" && !contentType.startsWith("image/")) throw new Error("Selecciona un archivo de imagen válido."); const path = createStoragePath(file, folder); const { error } = await supabaseClient.storage.from(SUPABASE_CONFIG.BUCKET).upload(path, file, { cacheControl: "3600", contentType, upsert: false }); if (error) { console.error("Error uploading file to Supabase Storage:", { rawError: error, message: error.message, statusCode: error.statusCode, error: error.error, bucket: SUPABASE_CONFIG.BUCKET, path, contentType }); throw new Error("No se pudo subir el archivo."); } return publicStorageUrl(path); }
function validateVideoFile(file) { const extension = fileExtension(file); if (!file || !file.size || !["mp4", "webm", "mov"].includes(extension)) throw new Error("Formato de video no permitido."); if (file.type && !Object.values(VIDEO_TYPES).includes(file.type)) throw new Error("El tipo de archivo de video no es válido."); }
async function uploadVideoToStorage(file, onProgress) { validateVideoFile(file); const path = createStoragePath(file, "videos"), contentType = mediaType(file); if (file.size <= LARGE_UPLOAD_BYTES) { onProgress?.(null); const { error } = await supabaseClient.storage.from(SUPABASE_CONFIG.BUCKET).upload(path, file, { cacheControl: "3600", contentType, upsert: true }); if (error) { console.error("Error uploading video to Supabase Storage:", { message: error.message, statusCode: error.statusCode, error: error.error, bucket: SUPABASE_CONFIG.BUCKET, path, contentType }); throw new Error("No se pudo subir el video."); } } else { if (!window.tus) throw new Error("El cargador de archivos grandes no está disponible."); const { data: { session } } = await supabaseClient.auth.getSession(); if (!session?.access_token) throw new Error("La sesión expiró."); const storageHost = new URL(SUPABASE_CONFIG.URL).hostname.replace(".supabase.co", ".storage.supabase.co"); await new Promise((resolve, reject) => { const upload = new window.tus.Upload(file, { endpoint: `https://${storageHost}/storage/v1/upload/resumable`, retryDelays: [0, 3000, 5000, 10000, 20000], chunkSize: LARGE_UPLOAD_BYTES, removeFingerprintOnSuccess: true, headers: { authorization: `Bearer ${session.access_token}`, "x-upsert": "true" }, metadata: { bucketName: SUPABASE_CONFIG.BUCKET, objectName: path, contentType, cacheControl: "3600" }, onError: error => { console.error("Resumable video upload failed:", { message: error.message, bucket: SUPABASE_CONFIG.BUCKET, path, contentType }); reject(error); }, onProgress: (uploaded, total) => onProgress?.(Math.round(uploaded / total * 100)), onSuccess: resolve }); upload.findPreviousUploads().then((previous) => { if (previous.length) upload.resumeFromPreviousUpload(previous[0]); upload.start(); }).catch(reject); }); } return { source: "storage", url: publicStorageUrl(path), original_url: publicStorageUrl(path), mime_type: contentType, title: file.name }; }
