[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Sitio estatico, sin build'"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
